site_name: DocumentDB-Kubernetes-Operator
repo_url: https://github.com/microsoft/documentdb-kubernetes-operator
theme:
  name: readthedocs

nav:
  - Version 1.0:
      - Get Started: v1/index.md
  - TLS Happy Paths: tls-happy-paths.md
  - Strict Local CA: strict-local-ca.md

plugins:
  - search

markdown_extensions:
  - admonition
  - toc:
      permalink: true