// Copyright (c) Microsoft Corporation.
// Licensed under the MIT License.

package otel

import (
	"crypto/sha256"
	_ "embed"
	"fmt"
	"sort"

	"gopkg.in/yaml.v3"

	dbpreview "github.com/documentdb/documentdb-operator/api/preview"
)

//go:embed base_config.yaml
var baseConfigYAML []byte

const defaultPrometheusPort = 8888

// collectorConfig represents the OTel Collector configuration structure.
type collectorConfig struct {
	Receivers  map[string]any `yaml:"receivers,omitempty"`
	Processors map[string]any `yaml:"processors,omitempty"`
	Exporters  map[string]any `yaml:"exporters,omitempty"`
	Service    *serviceConfig `yaml:"service,omitempty"`
}

type serviceConfig struct {
	Telemetry *telemetryConfig          `yaml:"telemetry,omitempty"`
	Pipelines map[string]pipelineConfig `yaml:"pipelines,omitempty"`
}

type telemetryConfig struct {
	Metrics *telemetryMetricsConfig `yaml:"metrics,omitempty"`
}

type telemetryMetricsConfig struct {
	Level   string `yaml:"level,omitempty"`
	Address string `yaml:"address,omitempty"`
}

type pipelineConfig struct {
	Receivers  []string `yaml:"receivers"`
	Processors []string `yaml:"processors,omitempty"`
	Exporters  []string `yaml:"exporters"`
}

// ConfigMapName returns the OTel ConfigMap name for a given DocumentDB cluster.
func ConfigMapName(clusterName string) string {
	return fmt.Sprintf("%s-otel-config", clusterName)
}

// GenerateConfigMapData returns the ConfigMap data entries for the OTel Collector.
// The config is split into two files that the collector merges at startup:
//   - static.yaml: receivers and batch processor from the embedded base_config.yaml.
//     Add new SQL metric queries to base_config.yaml — no Go code changes needed.
//   - dynamic.yaml: per-cluster resource attributes, exporters, and pipeline wiring.
//
// This function is only called when monitoring is enabled. When monitoring is
// disabled, the operator deletes the ConfigMap and removes sidecar parameters,
// then triggers a rolling restart (via restart annotation) so that CNPG
// recreates pods without the sidecar.
func GenerateConfigMapData(clusterName, namespace string, spec *dbpreview.MonitoringSpec) (map[string]string, error) {
	dynamicYAML, err := generateDynamicConfig(clusterName, namespace, spec)
	if err != nil {
		return nil, err
	}

	return map[string]string{
		"static.yaml":  string(baseConfigYAML),
		"dynamic.yaml": "# Auto-generated by documentdb-operator. Do not edit.\n" + dynamicYAML,
	}, nil
}

// generateDynamicConfig builds the per-cluster dynamic config: resource processor,
// exporters, and pipeline wiring. The OTel Collector deep-merges this with static.yaml.
func generateDynamicConfig(clusterName, namespace string, spec *dbpreview.MonitoringSpec) (string, error) {
	cfg := collectorConfig{
		Processors: map[string]any{
			"resource": map[string]any{
				"attributes": []map[string]any{
					{"key": "documentdb.cluster", "value": clusterName, "action": "upsert"},
					{"key": "k8s.namespace.name", "value": namespace, "action": "upsert"},
					{"key": "k8s.pod.name", "value": "${POD_NAME}", "action": "upsert"},
				},
			},
		},
	}

	exporterNames := []string{}

	if spec.Exporter != nil {
		if otlp := spec.Exporter.OTLP; otlp != nil && otlp.Endpoint != "" {
			if cfg.Exporters == nil {
				cfg.Exporters = map[string]any{}
			}
			cfg.Exporters["otlp"] = map[string]any{
				"endpoint": otlp.Endpoint,
				"tls": map[string]any{
					// TODO: Support TLS for OTLP exporter. Currently hardcoded to
					// insecure for in-cluster communication. When TLS is needed,
					// add TLS config fields to OTLPExporterSpec (certSecret, etc.).
					"insecure": true,
				},
			}
			exporterNames = append(exporterNames, "otlp")
		}

		if prom := spec.Exporter.Prometheus; prom != nil {
			if cfg.Exporters == nil {
				cfg.Exporters = map[string]any{}
			}
			port := prom.Port
			if port == 0 {
				port = defaultPrometheusPort
			}
			cfg.Exporters["prometheus"] = map[string]any{
				"endpoint": fmt.Sprintf("0.0.0.0:%d", port),
			}
			exporterNames = append(exporterNames, "prometheus")
		}
	}

	// Wire pipeline: receivers + batch from static.yaml, resource from this dynamic config.
	// Disable the collector's internal telemetry to avoid port conflicts with the
	// Prometheus exporter (both default to 8888).
	if len(exporterNames) > 0 {
		cfg.Service = &serviceConfig{
			Telemetry: &telemetryConfig{
				Metrics: &telemetryMetricsConfig{
					Level: "none",
				},
			},
			Pipelines: map[string]pipelineConfig{
				"metrics": {
					Receivers:  []string{"sqlquery"},
					Processors: []string{"resource", "batch"},
					Exporters:  exporterNames,
				},
			},
		}
	}

	out, err := yaml.Marshal(&cfg)
	if err != nil {
		return "", fmt.Errorf("failed to marshal dynamic OTel config: %w", err)
	}

	return string(out), nil
}

// HashConfigMapData computes a truncated SHA-256 hash of ConfigMap data.
// The hash is stored as a CNPG plugin parameter so that the operator detects
// config changes (via parameter diff in SyncCnpgCluster) and triggers a
// rolling restart via a restart annotation
// (e.g., operator upgrade adds new metrics, user changes exporter settings).
func HashConfigMapData(data map[string]string) string {
	h := sha256.New()
	keys := make([]string, 0, len(data))
	for k := range data {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		// Use length-prefixed format to avoid ambiguity between key/value boundaries.
		fmt.Fprintf(h, "%d:%s%d:%s;", len(k), k, len(data[k]), data[k])
	}
	return fmt.Sprintf("%x", h.Sum(nil))[:16]
}

// ResolvePrometheusPort returns the effective Prometheus port from the spec,
// or 0 if Prometheus exporter is not configured.
func ResolvePrometheusPort(spec *dbpreview.MonitoringSpec) int32 {
	if spec == nil || spec.Exporter == nil || spec.Exporter.Prometheus == nil {
		return 0
	}
	if spec.Exporter.Prometheus.Port == 0 {
		return defaultPrometheusPort
	}
	return spec.Exporter.Prometheus.Port
}
