apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: documentdb-operator-cluster-rolebinding
  labels:
    app.kubernetes.io/name: {{ include "documentdb-chart.name" . }}
    app.kubernetes.io/managed-by: "Helm"
subjects:
- kind: ServiceAccount
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: documentdb-operator-cluster-role
