# This rule is not used by the project documentdb-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over db.microsoft.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: documentdb-operator
    app.kubernetes.io/managed-by: kustomize
  name: documentdb-admin-role
rules:
- apiGroups:
  - db.microsoft.com
  resources:
  - documentdbs
  verbs:
  - '*'
- apiGroups:
  - db.microsoft.com
  resources:
  - documentdbs/status
  verbs:
  - get
