namespace: documentdb-operator
replicaCount: 1
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: "documentdb-operator"
image:
  documentdbk8soperator:
    # Updated to use ACR repository (operator image)
    repository: guanzhoutest.azurecr.io/documentdb/operator
    pullPolicy: Always
    # Tag overridden at install/upgrade time via --set image.documentdbk8soperator.tag=<TAG>
    tag: dev-placeholder
  sidecarinjector:
    # Updated to use ACR repository (sidecar gateway injector image)
    repository: guanzhoutest.azurecr.io/documentdb/sidecar
    pullPolicy: Always
    # Tag overridden at install/upgrade time via --set image.sidecarinjector.tag=<TAG>
    tag: dev-placeholder
cloudnative-pg:
  namespaceOverride: cnpg-system
