apiVersion: db.microsoft.com/preview
kind: DocumentDB
metadata:
  labels:
    app.kubernetes.io/name: documentdb-operator
    app.kubernetes.io/managed-by: kustomize
  name: documentdb-sample
spec:
  # TODO(user): Add fields here
