name: Copy ACR Image to GHCR

on:
  workflow_dispatch:
    inputs:
      registry:
        description: 'ACR registry name'
        required: true
        default: 'pgcosmoscontroller'
      repo:
        description: 'Repository name'
        required: true
        default: 'cnpg-plugin'
      tag:
        description: 'Image tag'
        required: true
        default: 'v13'

jobs:
  copy-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Docker login to ACR
        run: |
          az acr login --name ${{ github.event.inputs.registry }}

      - name: Login to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Pull image from ACR
        run: |
          docker pull ${{ github.event.inputs.registry }}.azurecr.io/${{ github.event.inputs.repo }}:${{ github.event.inputs.tag }}

      - name: Tag image for GHCR
        run: |
          docker tag ${{ github.event.inputs.registry }}.azurecr.io/${{ github.event.inputs.repo }}:${{ github.event.inputs.tag }} ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.event.inputs.repo }}:${{ github.event.inputs.tag }}

      - name: Push image to GHCR
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/${{ github.repository }}:${{ github.event.inputs.repo }}:${{ github.event.inputs.tag }}